name: bazel-container
description: setup minimal container for bazel build env
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - name: install g++12
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y g++-12
        sudo rm -f /usr/bin/g++
        sudo ln -s /usr/bin/g++-12 /usr/bin/g++
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - name: setup bazel cache
      if: ${{ !env.ACT }}
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
