name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-unittests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/bazel-container
      - name: unittests
        run: |
          bazel build --enable_bzlmod //...
          bazel test --enable_bzlmod //... --test_output=errors

  schema-validation:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/bazel-container
      - uses: actions/setup-go@v6
        with:
          go-version: "1.17.6"
      - name: pull validator
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          path: ocp-diag-core
          repository: opencomputeproject/ocp-diag-core
      - name: run validator against examples
        run: |
          OUTPUT="$(bazel run --enable_bzlmod //ocpdiag/core/examples/full_spec)"
          cd ocp-diag-core/validators/spec_validator
          echo "$OUTPUT" | go run . -schema ../../json_spec/output/root.json -
